# -*- coding: utf-8 -*-
"""CSE 436(final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyWnMUggIz-8oqdSe70r58zbDKQ1aDjP
"""

import pandas as pd
import numpy as np
import re
import nltk
import spacy
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

from imblearn.over_sampling import SMOTE
from prettytable import PrettyTable

# Deep Learning
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding, LSTM, GRU, Dense, Dropout,
    Bidirectional, BatchNormalization,
    Conv1D, GlobalMaxPooling1D
)
from tensorflow.keras.callbacks import EarlyStopping

nltk.download('stopwords')
nltk.download('wordnet')

nlp = spacy.load('en_core_web_sm')

df = pd.read_csv('/content/train.csv.zip')

print(df.shape)
df.head()

df['processed_tweet'] = df['tweet'].str.replace(r'[^a-zA-Z]', ' ', regex=True)
df.head()

df['processed_tweet_2'] = df['processed_tweet'].str.replace(r'[\s]+', ' ', regex=True)
df.head()

df['class'].replace({
    0: 'hate',
    1: 'offensive',
    2: 'neither'
}, inplace=True)

df.head()

def lemmatization_fast(texts):
    lemma_list = []

    for doc in nlp.pipe(texts, disable=['ner', 'parser'], batch_size=1000):
        lemma_list.append(' '.join([token.lemma_ for token in doc]))

    return lemma_list

df['lemma_tweet'] = lemmatization_fast(df['processed_tweet_2'].astype(str))

df[['tweet', 'lemma_tweet']].head()

X_cleaned = df['lemma_tweet']
y = df['class']

X_train_val, X_test_text, y_train_val, y_test = train_test_split(
    X_cleaned, y, test_size=0.15, random_state=42
)

X_train_text, X_val_text, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.1764, random_state=42
)

t = PrettyTable(['Dataset Split', 'Sample Count', 'Percentage (%)'])
total_len = len(df)

t.add_row(['Training Set', len(X_train_text), f"{(len(X_train_text)/total_len)*100:.1f}%"])
t.add_row(['Validation Set', len(X_val_text), f"{(len(X_val_text)/total_len)*100:.1f}%"])
t.add_row(['Test Set', len(X_test_text), f"{(len(X_test_text)/total_len)*100:.1f}%"])

print(t)

def generate_data_split_table_no_index(y_train, y_val, y_test):
    train_classes = pd.Series(y_train).value_counts()
    val_classes = pd.Series(y_val).value_counts()
    test_classes = pd.Series(y_test).value_counts()

    class_order = ['hate', 'offensive', 'neither']
    class_map = {
        'hate': "Hate Speech",
        'offensive': "Offensive Language",
        'neither': "Neither"
    }

    table = PrettyTable()
    table.title = "DETAILS OF DATA SPLIT"
    table.field_names = [
        "Class",
        "Total Instances",
        "Training Instances",
        "Validation Instances",
        "Testing Instances"
    ]

    total_inst_sum = 0
    total_train_sum = 0
    total_val_sum = 0
    total_test_sum = 0

    for cls in class_order:
        tr_c = train_classes.get(cls, 0)
        vl_c = val_classes.get(cls, 0)
        ts_c = test_classes.get(cls, 0)
        total_c = tr_c + vl_c + ts_c

        table.add_row([class_map[cls], total_c, tr_c, vl_c, ts_c])

        total_inst_sum += total_c
        total_train_sum += tr_c
        total_val_sum += vl_c
        total_test_sum += ts_c

    table.add_row(
        ["Total", total_inst_sum, total_train_sum, total_val_sum, total_test_sum],
        divider=True
    )

    print(table)

generate_data_split_table_no_index(y_train, y_val, y_test)

print("Training ML Models ---")

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_tfidf, y_train)

ml_models = {
    "LR": LogisticRegression(max_iter=1000),
    "SVM": SVC(kernel='linear'),
    "RF": RandomForestClassifier(n_estimators=100, random_state=42),
    "NB": MultinomialNB(),
    "GBM": GradientBoostingClassifier(random_state=42)
}

results_acc = {}
metrics_data = []

for name, model in ml_models.items():
    model.fit(X_train_res, y_train_res)
    y_pred = model.predict(X_test_tfidf)

    results_acc[name] = accuracy_score(y_test, y_pred) * 100

    metrics_data.append({
        'Model': name,
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-score': f1_score(y_test, y_pred, average='weighted')
    })

    print(f"{name} trained.")

print("\n--- Deep Learning Model Training (BiLSTM, GRU, CNN) ---")

vocab_size = 10000
sentence_length = 50
embedding_dim = 100
num_classes = 3

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_text)

X_train_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_train_text),
    maxlen=sentence_length,
    padding='post',
    truncating='post'
)

X_val_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_val_text),
    maxlen=sentence_length,
    padding='post',
    truncating='post'
)

X_test_pad = pad_sequences(
    tokenizer.texts_to_sequences(X_test_text),
    maxlen=sentence_length,
    padding='post',
    truncating='post'
)

le = LabelEncoder()

y_train_encoded = le.fit_transform(y_train)
y_val_encoded = le.transform(y_val)
y_test_encoded = le.transform(y_test)

bilstm_model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=sentence_length),
    Bidirectional(LSTM(64, return_sequences=True)),
    BatchNormalization(),
    Dropout(0.3),
    LSTM(32),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

gru_model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=sentence_length),
    GRU(64, return_sequences=True),
    BatchNormalization(),
    Dropout(0.3),
    GRU(32),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

cnn_model = Sequential([
    Embedding(vocab_size, embedding_dim, input_length=sentence_length),
    Conv1D(filters=128, kernel_size=5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

dl_models = {
    'BiLSTM': bilstm_model,
    'GRU': gru_model,
    'CNN': cnn_model
}

dl_histories = {}
dl_predictions = {}
dl_proba_preds = {}
dl_test_accuracies = {}

for model_name, model in dl_models.items():
    print(f"\nTraining {model_name}...")

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        X_train_pad, y_train_encoded,
        validation_data=(X_val_pad, y_val_encoded),
        epochs=10,
        batch_size=32,

        verbose=1
    )

    dl_histories[model_name] = history

    y_pred_proba = model.predict(X_test_pad)
    y_pred = np.argmax(y_pred_proba, axis=-1)
    dl_predictions[model_name] = y_pred
    dl_proba_preds[model_name] = y_pred_proba

    test_loss, test_accuracy = model.evaluate(X_test_pad, y_test_encoded, verbose=0)
    dl_test_accuracies[model_name] = test_accuracy * 100
    results_acc[model_name] = test_accuracy * 100

    metrics_data.append({
        'Model': model_name,
        'Precision': precision_score(y_test_encoded, y_pred, average='weighted'),
        'Recall': recall_score(y_test_encoded, y_pred, average='weighted'),
        'F1-score': f1_score(y_test_encoded, y_pred, average='weighted')
    })

    print(f"{model_name} Test Accuracy: {test_accuracy * 100:.2f}%")

best_dl_model_name = max(dl_test_accuracies, key=dl_test_accuracies.get)
best_dl_model = dl_models[best_dl_model_name]
y_pred_dl = dl_predictions[best_dl_model_name]

print(f"\nBest Deep Learning Model: {best_dl_model_name} ({dl_test_accuracies[best_dl_model_name]:.2f}%")

ml_model_names = ["LR", "SVM", "RF", "NB", "GBM"]

best_ml_model_name = max(ml_model_names, key=lambda x: results_acc[x])
best_ml_accuracy = results_acc[best_ml_model_name]

print("Best ML Model:", best_ml_model_name)
print("Best ML Accuracy:", round(best_ml_accuracy, 2), "%")

metrics_data = []
results_acc = {}
ml_predictions = {}
ml_probabilities = {}
trained_ml_models = {}

# Redefine ml_models here to ensure SVC has probability=True
ml_models = {
    "LR": LogisticRegression(max_iter=1000),
    "SVM": SVC(kernel='linear', probability=True), # Corrected: added probability=True
    "RF": RandomForestClassifier(n_estimators=100, random_state=42),
    "NB": MultinomialNB(),
    "GBM": GradientBoostingClassifier(random_state=42)
}

print("\nTraining Machine Learning Models...\n")

for name, model in ml_models.items():
    model.fit(X_train_res, y_train_res)

    y_pred = model.predict(X_test_tfidf)
    # Only call predict_proba if the model supports it
    if hasattr(model, 'predict_proba'):
        y_prob = model.predict_proba(X_test_tfidf)
    else:
        # For models like SVC without probability=True, set a placeholder or handle as needed
        # This else block should theoretically not be hit after the fix
        y_prob = None # Or raise an error if probabilities are strictly required

    trained_ml_models[name] = model
    ml_predictions[name] = y_pred
    ml_probabilities[name] = y_prob

    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    acc = accuracy_score(y_test, y_pred)

    metrics_data.append({
        'Model': name,
        'Precision': precision,
        'Recall': recall,
        'F1-score': f1
    })

    results_acc[name] = acc * 100

    print(f"{name} trained successfully. Accuracy = {acc:.4f}")

# Removed the redundant ml_models redefinition from here.

dl_predictions = {}
dl_probabilities = {}
trained_dl_models = {}

print("\nTraining Deep Learning Models...\n")

early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

for name, model in dl_models.items():
    print(f"\nTraining {name}...")

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        X_train_pad,
        y_train_encoded,
        validation_data=(X_val_pad, y_val_encoded),
        epochs=10,
        batch_size=32,
        callbacks=[early_stop],
        verbose=1
    )

    y_prob_dl = model.predict(X_test_pad)
    y_pred_dl = np.argmax(y_prob_dl, axis=-1)

    trained_dl_models[name] = model
    dl_probabilities[name] = y_prob_dl
    dl_predictions[name] = y_pred_dl

    precision = precision_score(y_test_encoded, y_pred_dl, average='weighted')
    recall = recall_score(y_test_encoded, y_pred_dl, average='weighted')
    f1 = f1_score(y_test_encoded, y_pred_dl, average='weighted')
    acc = accuracy_score(y_test_encoded, y_pred_dl)

    metrics_data.append({
        'Model': name,
        'Precision': precision,
        'Recall': recall,
        'F1-score': f1
    })

    results_acc[name] = acc * 100

    print(f"{name} Accuracy = {acc:.4f}")

best_ml_probs = ml_probabilities[best_ml_model_name]
best_dl_probs = dl_probabilities[best_dl_model_name]

print("Best ML model used for fusion:", best_ml_model_name)
print("Best DL model used for fusion:", best_dl_model_name)
print("ML prob shape:", best_ml_probs.shape)
print("DL prob shape:", best_dl_probs.shape)

ml_acc_norm = results_acc[best_ml_model_name] / 100
dl_acc_norm = results_acc[best_dl_model_name] / 100

total_score = ml_acc_norm + dl_acc_norm

ml_weight = ml_acc_norm / total_score
dl_weight = dl_acc_norm / total_score

print("ML Weight:", round(ml_weight, 3))
print("DL Weight:", round(dl_weight, 3))

fused_probs = (ml_weight * best_ml_probs) + (dl_weight * best_dl_probs)

fused_pred_indices = np.argmax(fused_probs, axis=1)
fused_pred_labels = le.inverse_transform(fused_pred_indices)

fusion_model_name = f"{best_ml_model_name}+{best_dl_model_name} Fusion"

fusion_precision = precision_score(y_test, fused_pred_labels, average='weighted')
fusion_recall = recall_score(y_test, fused_pred_labels, average='weighted')
fusion_f1 = f1_score(y_test, fused_pred_labels, average='weighted')
fusion_acc = accuracy_score(y_test, fused_pred_labels)

fusion_metrics = {
    'Model': fusion_model_name,
    'Precision': fusion_precision,
    'Recall': fusion_recall,
    'F1-score': fusion_f1,
    'Accuracy': fusion_acc
}

print("Fusion Accuracy:", round(fusion_acc, 4))
print("Fusion Precision:", round(fusion_precision, 4))
print("Fusion Recall:", round(fusion_recall, 4))
print("Fusion F1-score:", round(fusion_f1, 4))

main_table = PrettyTable()
main_table.field_names = ["Classifier", "P", "R", "F", "A"]

added_models = set()

for row in metrics_data:
    model_name = row['Model']

    if model_name in added_models:
        continue

    added_models.add(model_name)

    precision = row['Precision']
    recall = row['Recall']
    f1 = row['F1-score']
    accuracy = results_acc[model_name] / 100

    main_table.add_row([
        model_name,
        round(precision, 3),
        round(recall, 3),
        round(f1, 3),
        round(accuracy, 3)
    ])

print("\nMain Model Comparison Table\n")
print(main_table)

fusion_table = PrettyTable()
fusion_table.field_names = [
    "Fusion Model",
    "Best ML",
    "Best DL",
    "P",
    "R",
    "F",
    "A"
]

fusion_table.add_row([
    fusion_model_name,
    best_ml_model_name,
    best_dl_model_name,
    round(fusion_metrics['Precision'], 3),
    round(fusion_metrics['Recall'], 3),
    round(fusion_metrics['F1-score'], 3),
    round(fusion_metrics['Accuracy'], 3)
])

print("\nFusion Result Table\n")
print(fusion_table)

import matplotlib.pyplot as plt

# Use perf_df
plot_df = perf_df.copy()

# X positions
x = range(len(plot_df))
width = 0.25

plt.figure()

# Bars
plt.bar([i - width for i in x], plot_df['Precision'], width=width, label='Precision')
plt.bar([i for i in x], plot_df['Recall'], width=width, label='Recall')
plt.bar([i + width for i in x], plot_df['F1-score'], width=width, label='F1-score')

# Labels & Title

plt.ylabel('Score')
plt.ylim(0, 1.05)

plt.xticks(list(x), plot_df['Model'], rotation=45)
plt.legend()

plt.tight_layout()
plt.show()

# ==============================
# Label Mapping
# ==============================

label_map = {
    0: "hate",
    1: "offensive",
    2: "neither"
}
# ==============================
# Convert Predicted Labels
# ==============================

y_pred_named = [
    label_map[label]
    for label in y_pred_fusion
]

y_test_named = [
    label_map[label]
    if isinstance(label, int)
    else label
    for label in y_test
]
import pandas as pd

error_df = pd.DataFrame({
    "Text Sample": X_test_text,
    "Actual": y_test_named,
    "Predicted": y_pred_named
})

# শুধু ভুলগুলো
misclassified = error_df[
    error_df["Actual"] != error_df["Predicted"]
]

misclassified_sample = misclassified.head(10)

print(misclassified_sample)

# Confusion Matrix for Fusion Model
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm_fusion = confusion_matrix(y_test_encoded, y_pred_fusion)
class_names = list(le.classes_)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_fusion, annot=True, fmt='d', cmap='Greens',
            xticklabels=class_names,
            yticklabels=class_names,
            annot_kws={"size": 13})
plt.xlabel('Predicted Class', fontsize=12)
plt.ylabel('True Class', fontsize=12)
plt.tight_layout()
plt.savefig('confusion_matrix_fusion.png', dpi=200)
plt.show()