# -*- coding: utf-8 -*-
"""CSE 436(final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyWnMUggIz-8oqdSe70r58zbDKQ1aDjP
"""

import pandas as pd
import numpy as np
import re
import nltk
import spacy
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

from imblearn.over_sampling import SMOTE
from prettytable import PrettyTable

# Deep Learning
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding, LSTM, GRU, Dense, Dropout,
    Bidirectional, BatchNormalization,
    Conv1D, GlobalMaxPooling1D
)
from tensorflow.keras.callbacks import EarlyStopping

nltk.download('stopwords')
nltk.download('wordnet')

nlp = spacy.load('en_core_web_sm')

df = pd.read_csv('/content/train.csv.zip')

print(df.shape)
df.head()

df['processed_tweet'] = df['tweet'].str.replace(r'[^a-zA-Z]', ' ', regex=True)
df.head()

df['processed_tweet_2'] = df['processed_tweet'].str.replace(r'[\s]+', ' ', regex=True)
df.head()

df['class'].replace({
    0: 'hate',
    1: 'offensive',
    2: 'neither'
}, inplace=True)

df.head()

def lemmatization_fast(texts):
    lemma_list = []

    for doc in nlp.pipe(texts, disable=['ner', 'parser'], batch_size=1000):
        lemma_list.append(' '.join([token.lemma_ for token in doc]))

    return lemma_list

df['lemma_tweet'] = lemmatization_fast(df['processed_tweet_2'].astype(str))

df[['tweet', 'lemma_tweet']].head()

X_cleaned = df['lemma_tweet']
y = df['class']

X_train_val, X_test_text, y_train_val, y_test = train_test_split(
    X_cleaned, y, test_size=0.15, random_state=42
)

X_train_text, X_val_text, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.1764, random_state=42
)

def generate_data_split_table_no_index(y_train, y_val, y_test):
    train_classes = pd.Series(y_train).value_counts()
    val_classes = pd.Series(y_val).value_counts()
    test_classes = pd.Series(y_test).value_counts()

    class_order = ['hate', 'offensive', 'neither']
    class_map = {
        'hate': "Hate Speech",
        'offensive': "Offensive Language",
        'neither': "Neither"
    }

    table = PrettyTable()
    table.field_names = [
        "Class",
        "Total Instances",
        "Training Instances",
        "Validation Instances",
        "Testing Instances"
    ]

    total_inst_sum = 0
    total_train_sum = 0
    total_val_sum = 0
    total_test_sum = 0

    for cls in class_order:
        tr_c = train_classes.get(cls, 0)
        vl_c = val_classes.get(cls, 0)
        ts_c = test_classes.get(cls, 0)
        total_c = tr_c + vl_c + ts_c

        table.add_row([class_map[cls], total_c, tr_c, vl_c, ts_c])

        total_inst_sum += total_c
        total_train_sum += tr_c
        total_val_sum += vl_c
        total_test_sum += ts_c

    table.add_row(
        ["Total", total_inst_sum, total_train_sum, total_val_sum, total_test_sum],
        divider=True
    )

    print(table)

generate_data_split_table_no_index(y_train, y_val, y_test)

print("Training ML Models ---")

tfidf = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_val_tfidf   = tfidf.transform(X_val_text)
X_test_tfidf  = tfidf.transform(X_test_text)

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_tfidf, y_train)

metrics_data       = []
results_acc        = {}
ml_predictions     = {}
ml_probabilities   = {}
trained_ml_models  = {}

ml_models = {
    "LR":  LogisticRegression(max_iter=1000),
    "SVM": SVC(kernel='linear', probability=True),
    "RF":  RandomForestClassifier(n_estimators=100, random_state=42),
    "NB":  MultinomialNB(),
    "GBM": GradientBoostingClassifier(random_state=42)
}

print("\nTraining Machine Learning Models...\n")
for name, model in ml_models.items():
    model.fit(X_train_res, y_train_res)
    y_pred = model.predict(X_test_tfidf)
    y_prob = model.predict_proba(X_test_tfidf)

    trained_ml_models[name]  = model
    ml_predictions[name]     = y_pred
    ml_probabilities[name]   = y_prob

    precision = precision_score(y_test, y_pred, average='weighted')
    recall    = recall_score(y_test, y_pred, average='weighted')
    f1        = f1_score(y_test, y_pred, average='weighted')
    acc       = accuracy_score(y_test, y_pred)

    metrics_data.append({'Model': name, 'Precision': precision, 'Recall': recall, 'F1-score': f1})
    results_acc[name] = acc * 100
    print(f"{name} trained. Accuracy = {acc:.4f}")

print("\n--- Optimized Deep Learning Model Training ---")

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import *
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

# ---------------- PARAMETERS ----------------
vocab_size = 10000
sentence_length = 60   # optimized
embedding_dim = 100
num_classes = 3

# ---------------- TOKENIZATION ----------------
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_text)

def make_pad(texts):
    return pad_sequences(
        tokenizer.texts_to_sequences(texts),
        maxlen=sentence_length,
        padding='post',
        truncating='post'
    )

X_train_pad = make_pad(X_train_text)
X_val_pad   = make_pad(X_val_text)
X_test_pad  = make_pad(X_test_text)

# ---------------- LABEL ENCODING ----------------
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_val_enc   = le.transform(y_val)
y_test_enc  = le.transform(y_test)

# ---------------- CLASS WEIGHT ----------------
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_enc),
    y=y_train_enc
)
class_weight_dict = dict(enumerate(class_weights))

# ---------------- CALLBACKS ----------------
early_stop = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
reduce_lr  = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2)

# =====================================================
# 🔥 MODEL 1: BiLSTM
# =====================================================
bilstm_model = Sequential([
    Embedding(vocab_size, embedding_dim),
    SpatialDropout1D(0.2),
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(32)),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# =====================================================
# 🔥 MODEL 2: GRU (Simplified)
# =====================================================
gru_model = Sequential([
    Embedding(vocab_size, embedding_dim),
    SpatialDropout1D(0.2),
    GRU(64),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(num_classes, activation='softmax')
])

# =====================================================
# 🔥 MODEL 3: CNN (Simplified → better accuracy)
# =====================================================
cnn_model = Sequential([
    Embedding(vocab_size, embedding_dim),
    Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

# =====================================================
# 🔥 MODEL 4: CNN + BiLSTM (Hybrid)
# =====================================================
def build_cnn_bilstm():
    inp = Input(shape=(sentence_length,))
    x = Embedding(vocab_size, embedding_dim)(inp)
    x = Conv1D(128, 5, activation='relu')(x)
    x = MaxPooling1D(2)(x)
    x = Bidirectional(LSTM(64))(x)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.4)(x)
    out = Dense(num_classes, activation='softmax')(x)
    return Model(inp, out)

cnn_bilstm_model = build_cnn_bilstm()

# ---------------- MODEL LIST ----------------
dl_models = {
    'BiLSTM': bilstm_model,
    'GRU': gru_model,
    'CNN': cnn_model,
    'CNN-BiLSTM': cnn_bilstm_model
}

# ---------------- STORAGE ----------------
dl_results = {}
dl_probabilities = {} # Initialize dl_probabilities
trained_dl_models = {} # Initialize trained_dl_models

# =====================================================
# 🚀 TRAINING LOOP
# =====================================================
for name, model in dl_models.items():
    print(f"\nTraining {name}...")

    model.compile(
        optimizer=Adam(learning_rate=3e-4),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        X_train_pad, y_train_enc,
        validation_data=(X_val_pad, y_val_enc),
        epochs=12,
        batch_size=32,
        class_weight=class_weight_dict,
        callbacks=[early_stop, reduce_lr],
        verbose=1
    )

    # Prediction
    y_prob = model.predict(X_test_pad) # Get raw probabilities for fusion
    y_pred = np.argmax(y_prob, axis=-1)

    # Store probabilities and trained models
    dl_probabilities[name] = y_prob
    trained_dl_models[name] = model

    # Metrics
    acc = accuracy_score(y_test_enc, y_pred)
    precision = precision_score(y_test_enc, y_pred, average='weighted')
    recall = recall_score(y_test_enc, y_pred, average='weighted')
    f1 = f1_score(y_test_enc, y_pred, average='weighted')

    dl_results[name] = {
        'Accuracy': acc,
        'Precision': precision,
        'Recall': recall,
        'F1-score': f1
    }

    print(f"{name} → Acc: {acc:.4f}, F1: {f1:.4f}")

from tabulate import tabulate
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import numpy as np

results = []

# ---------------- ML Models ----------------
ml_models = {
    "LR": trained_ml_models["LR"],
    "SVM": trained_ml_models["SVM"],
    "RF": trained_ml_models["RF"],
    "NB": trained_ml_models["NB"],
    "GBM": trained_ml_models["GBM"]
}

for name, model in ml_models.items():
    y_pred = model.predict(X_test_tfidf) # Use X_test_tfidf for ML models

    p = precision_score(y_test, y_pred, average='weighted')
    r = recall_score(y_test, y_pred, average='weighted')
    f = f1_score(y_test, y_pred, average='weighted')
    a = accuracy_score(y_test, y_pred)

    results.append([name, round(p,3), round(r,3), round(f,3), round(a,3)])


# ---------------- DL Models ----------------
dl_models = {
    "BiLSTM": trained_dl_models["BiLSTM"],
    "GRU": trained_dl_models["GRU"],
    "CNN": trained_dl_models["CNN"],
    "CNN-BiLSTM": trained_dl_models["CNN-BiLSTM"] # Include CNN-BiLSTM
}

for name, model in dl_models.items():

    # Keras models use X_test_pad
    y_prob_dl = model.predict(X_test_pad)

    # If probability output, convert to class labels
    y_pred_dl = np.argmax(y_prob_dl, axis=1)

    # Evaluate against integer-encoded test labels
    p = precision_score(y_test_enc, y_pred_dl, average='weighted')
    r = recall_score(y_test_enc, y_pred_dl, average='weighted')
    f = f1_score(y_test_enc, y_pred_dl, average='weighted')
    a = accuracy_score(y_test_enc, y_pred_dl)

    results.append([name, round(p,3), round(r,3), round(f,3), round(a,3)])


# ---------------- Table Output ----------------
headers = ["Classifier", "P", "R", "F", "A"]

print(tabulate(results, headers=headers, tablefmt="grid"))

# Top-3 ML and Top-3 DL by F1-score — with full metrics table
ml_names = ["LR", "SVM", "RF", "NB", "GBM"]
dl_names = ["BiLSTM", "GRU", "CNN", "CNN-BiLSTM"]

# Ensure metrics_data includes DL model results
# Based on the execution history, dl_results was populated but not merged into metrics_data
for name, res in dl_results.items():
    # Only add if not already present, to avoid duplicates if cell is re-run
    if not any(d.get('Model') == name for d in metrics_data):
        metrics_data.append({
            'Model': name,
            'Precision': res['Precision'],
            'Recall': res['Recall'],
            'F1-score': res['F1-score']
        })
    # Also update results_acc for DL models as it's used later
    results_acc[name] = res['Accuracy'] * 100 # Assuming 'Accuracy' in dl_results is a 0-1 float

f1_lookup = {d['Model']: d['F1-score'] for d in metrics_data}

top3_ml = sorted(ml_names, key=lambda m: f1_lookup[m], reverse=True)[:3]
top3_dl = sorted(dl_names, key=lambda m: f1_lookup[m], reverse=True)[:3]

print("Top-3 ML models by F1:", top3_ml)
print("Top-3 DL models by F1:", top3_dl)

# --- Table: Top-3 ML ---
ml_table = PrettyTable()
ml_table.field_names = ["Rank", "ML Model", "Precision", "Recall", "F1-score", "Accuracy"]
ml_table.align = "r"
ml_table.align["ML Model"] = "l"
for rank, name in enumerate(top3_ml, 1):
    row = next(d for d in metrics_data if d['Model'] == name)
    ml_table.add_row([rank, name,
                      f"{row['Precision']:.4f}",
                      f"{row['Recall']:.4f}",
                      f"{row['F1-score']:.4f}",
                      f"{results_acc[name]/100:.4f}"])
print(ml_table)

# --- Table: Top-3 DL ---
dl_table = PrettyTable()
dl_table.field_names = ["Rank", "DL Model", "Precision", "Recall", "F1-score", "Accuracy"]
dl_table.align = "r"
dl_table.align["DL Model"] = "l"
for rank, name in enumerate(top3_dl, 1):
    row = next(d for d in metrics_data if d['Model'] == name)
    dl_table.add_row([rank, name,
                      f"{row['Precision']:.4f}",
                      f"{row['Recall']:.4f}",
                      f"{row['F1-score']:.4f}",
                      f"{results_acc[name]/100:.4f}"])
print(dl_table)

# 3x3 Fusion: All combinations of Top-3 ML x Top-3 DL

fusion_results = []

for ml_name in top3_ml:
    for dl_name in top3_dl:
        ml_probs = ml_probabilities[ml_name]
        dl_probs = dl_probabilities[dl_name]

        w_ml = results_acc[ml_name] / 100
        w_dl = results_acc[dl_name] / 100
        total = w_ml + w_dl
        w_ml /= total
        w_dl /= total

        fused_probs  = w_ml * ml_probs + w_dl * dl_probs
        fused_idx    = np.argmax(fused_probs, axis=1)
        fused_labels = le.inverse_transform(fused_idx)

        p  = precision_score(y_test, fused_labels, average='weighted')
        r  = recall_score(y_test, fused_labels, average='weighted')
        f1 = f1_score(y_test, fused_labels, average='weighted')
        a  = accuracy_score(y_test, fused_labels)

        fusion_results.append({
            'Fusion Name': f"{ml_name}+{dl_name}",
            'Precision': p, 'Recall': r, 'F1-score': f1, 'Accuracy': a,
            'fused_labels': fused_labels
        })

fusion_results.sort(key=lambda x: x['F1-score'], reverse=True)

fusion_table = PrettyTable()
fusion_table.field_names = ["#", "Fusion (ML + DL)","Precision", "Recall", "F1-score", "Accuracy"]
fusion_table.align = "r"
fusion_table.align["Fusion (ML + DL)"] = "l"

for i, res in enumerate(fusion_results, 1):
    fusion_table.add_row([
        i, res['Fusion Name'],
        f"{res['Precision']:.4f}", f"{res['Recall']:.4f}",
        f"{res['F1-score']:.4f}",  f"{res['Accuracy']:.4f}"
    ])


print(fusion_table)

best_fusion       = fusion_results[0]
fusion_model_name = best_fusion['Fusion Name']
y_pred_fusion     = le.transform(best_fusion['fused_labels'])

# Performance bar chart for all models
import matplotlib.pyplot as plt

seen, unique_models = set(), []
for d in metrics_data:
    if d['Model'] not in seen:
        seen.add(d['Model'])
        unique_models.append(d)

perf_df = pd.DataFrame(unique_models)
x     = range(len(perf_df))
width = 0.25

fig, ax = plt.subplots(figsize=(14, 5))
bars1 = ax.bar([i - width for i in x], perf_df['Precision'], width=width, label='Precision', color='steelblue')
bars2 = ax.bar([i           for i in x], perf_df['Recall'],    width=width, label='Recall',    color='darkorange')
bars3 = ax.bar([i + width for i in x], perf_df['F1-score'],   width=width, label='F1-score',  color='seagreen')

ax.set_ylabel('Score')
ax.set_ylim(0, 1.15)
ax.set_xticks(list(x))
ax.set_xticklabels(perf_df['Model'], rotation=45, ha='right', fontsize=10)
ax.set_title('Model Performance Comparison — All Models', fontsize=13)
ax.legend()

for bars in [bars1, bars2, bars3]:
    for bar in bars:
        ax.annotate(f'{bar.get_height():.2f}',
                    xy=(bar.get_x() + bar.get_width() / 2, bar.get_height()),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom', fontsize=7)
plt.tight_layout()
plt.show()

# Confusion Matrix — Best Fusion Model
from sklearn.metrics import confusion_matrix
import seaborn as sns

cm_fusion   = confusion_matrix(y_test_encoded, y_pred_fusion)
class_names = list(le.classes_)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_fusion, annot=True, fmt='d', cmap='Greens',
            xticklabels=class_names, yticklabels=class_names,
            annot_kws={"size": 13})
plt.xlabel('Predicted Class', fontsize=12)
plt.ylabel('True Class', fontsize=12)
plt.tight_layout()
plt.savefig('confusion_matrix_fusion.png', dpi=200)
plt.show()

label_map_inv = {i: cls for i, cls in enumerate(le.classes_)}
y_pred_str = [label_map_inv[i] for i in y_pred_fusion]

error_df = pd.DataFrame({
    'Text Sample': list(X_test_text),
    'Actual':      list(y_test),
    'Predicted':   y_pred_str
})
error_df['Status'] = error_df.apply(
    lambda r: 'Correct' if r['Actual'] == r['Predicted'] else 'Misclassified', axis=1
)

misclassified = error_df[error_df['Status'] == 'Misclassified']
correct       = error_df[error_df['Status'] == 'Correct']

# 3 correct + 5 misclassified (like the paper)
sample_correct = correct.sample(n=3, random_state=42)
sample_wrong   = misclassified.sample(n=5, random_state=42)

# Correct first, then misclassified
table_df = pd.concat([sample_correct, sample_wrong]).reset_index(drop=True)

# Shorten text to ~40 chars
def shorten(text, n=40):
    return (text[:n] + '...') if len(str(text)) > n else str(text)

table_df['Text Sample (Short)'] = table_df['Text Sample'].apply(shorten)

# Print as clean table
print(f"{'Text Sample (Short)':<45} {'Actual':<12} {'Pred.':<12} {'Status'}")
print("-" * 85)
for _, row in table_df.iterrows():
    print(f"{row['Text Sample (Short)']:<45} {row['Actual']:<12} {row['Predicted']:<12} {row['Status']}")

# Overall stats
total = len(error_df)
miss  = len(misclassified)