# -*- coding: utf-8 -*-
"""CSE 436(final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hyWnMUggIz-8oqdSe70r58zbDKQ1aDjP
"""

import pandas as pd
import numpy as np
import re
import nltk
import spacy
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer # Added this import
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE
from prettytable import PrettyTable

# Deep Learning
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional, BatchNormalization, Conv1D, MaxPooling1D, GlobalMaxPooling1D # Added Conv1D, MaxPooling1D, GlobalMaxPooling1D
from tensorflow.keras.callbacks import EarlyStopping # Added EarlyStopping

# Resources
nltk.download('stopwords')
nltk.download('wordnet') # Added this download
nlp = spacy.load('en_core_web_sm')

df = pd.read_csv('/content/train.csv.zip')

df.shape

df.head()

"""REPLACING SYMBOLS AND NUMBERS FROM TEXT"""

df['processed_tweet'] = df['tweet'].str.replace(r'[^a-zA-Z]', ' ', regex = True)

df

df['processed_tweet'].iloc[0]

df['processed_tweet'].iloc[100]

""" REPLACING MULTIPLE WHITESPACE CHARACTERS WITH SINGLE ONE"""

df['processed_tweet_2'] = df['processed_tweet'].str.replace(r'[\s]+', ' ', regex = True)

df['processed_tweet_2'].iloc[0]

df['processed_tweet_2'].iloc[100]

df['processed_tweet_2'].iloc[1000]

df.head()

"""REPLACING THE TARGET VALUES"""

df['class'].replace({0 : 'hate', 1 : 'offensive', 2 : 'neither'}, inplace = True)

df.head()

"""load out spacy modeule"""

nlp = spacy.load('en_core_web_sm')

# SpaCy-র ভারী অংশগুলো বাদ দিয়ে শুধুমাত্র লেমাটাইজেশন করা
def lemmatization_fast(texts):
    lemma_list = []
    # disable=['ner', 'parser'] দিলে কোড অনেক দ্রুত চলবে
    for doc in nlp.pipe(texts, disable=['ner', 'parser'], batch_size=1000):
        lemma_list.append(' '.join([word.lemma_ for word in doc]))
    return lemma_list

# .apply() এর বদলে সরাসরি পুরো কলাম পাস করুন
df['lemma_tweet'] = lemmatization_fast(df['processed_tweet_2'].astype(str))

# বাকি অংশ আগের মতোই থাকবে
X_cleaned = df['lemma_tweet']
y = df['class']

X_train_val, X_test_text, y_train_val, y_test = train_test_split(X_cleaned, y, test_size=0.15, random_state=42)
X_train_text, X_val_text, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.1764, random_state=42)

# টেবিল প্রিন্ট
from prettytable import PrettyTable
t = PrettyTable(['Dataset Split', 'Sample Count', 'Percentage (%)'])
total_len = len(df)
t.add_row(['Training Set', len(X_train_text), f"{(len(X_train_text)/total_len)*100:.1f}%"])
t.add_row(['Validation Set', len(X_val_text), f"{(len(X_val_text)/total_len)*100:.1f}%"])
t.add_row(['Test Set', len(X_test_text), f"{(len(X_test_text)/total_len)*100:.1f}%"])
print(t)

from prettytable import PrettyTable
import pandas as pd

# ১. ফাংশন ডেফিনিশন (এটি শুধু নিয়ম বা রেসিপি)
def generate_data_split_table_no_index(y_train, y_val, y_test):
    train_classes = pd.Series(y_train).value_counts().sort_index()
    val_classes = pd.Series(y_val).value_counts().sort_index()
    test_classes = pd.Series(y_test).value_counts().sort_index()

    class_map = {
        0: "Hate Speech",
        1: "Not offensive",
        2: "Offensive but not Hate Speech"
    }

    table = PrettyTable()
    table.title = "TABLE II. DETAILS OF DATA SPLIT"
    table.field_names = ["Class", "Total Instances", "Training Instances", "Validation Instances", "Testing Instances"]

    total_inst_sum = total_train_sum = total_val_sum = total_test_sum = 0

    for cls in sorted(class_map.keys()):
        tr_c = train_classes.get(cls, 0)
        vl_c = val_classes.get(cls, 0)
        ts_c = test_classes.get(cls, 0)
        total_c = tr_c + vl_c + ts_c

        table.add_row([class_map[cls], total_c, tr_c, vl_c, ts_c])

        total_inst_sum += total_c
        total_train_sum += tr_c
        total_val_sum += vl_c
        total_test_sum += ts_c

    table.add_row(["Total", total_inst_sum, total_train_sum, total_val_sum, total_test_sum], divider=True)
    print(table)

generate_data_split_table_no_index(y_train, y_val, y_test)

print(" Training ML Models ---")
tfidf = TfidfVectorizer(max_features=5000)
X_train_tfidf = tfidf.fit_transform(X_train_text)
X_test_tfidf = tfidf.transform(X_test_text)

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_tfidf, y_train)

ml_models = {
    "LR": LogisticRegression(max_iter=1000),
    "SVM": SVC(kernel='linear'),
    "RF": RandomForestClassifier(n_estimators=100),
    "NB": MultinomialNB(),
    "GBM": GradientBoostingClassifier()
}

results_acc = {}
metrics_data = []

for name, model in ml_models.items():
    model.fit(X_train_res, y_train_res)
    y_pred = model.predict(X_test_tfidf)
    results_acc[name] = accuracy_score(y_test, y_pred) * 100
    metrics_data.append({
        'Model': name,
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-score': f1_score(y_test, y_pred, average='weighted')
    })
    print(f"{name} trained.")

print("\n Bidirectional LSTM Training ---")
vocab_size = 10000
sentence_length = 50

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(X_train_text)

X_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train_text), maxlen=sentence_length)
X_test_pad = pad_sequences(tokenizer.texts_to_sequences(X_test_text), maxlen=sentence_length)

# Encode target labels to integers
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

# LSTM Architecture (Optimized)
lstm_model = Sequential([
    Embedding(vocab_size, 100),
    Bidirectional(LSTM(64, return_sequences=True)),
    BatchNormalization(),
    Dropout(0.3),
    LSTM(32),
    Dense(32, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax') # 3 classes: hate, offensive, neither
])

lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
lstm_model.fit(X_train_pad, y_train_encoded, epochs=10, batch_size=32, verbose=1)

# Evaluation
y_pred_dl = np.argmax(lstm_model.predict(X_test_pad), axis=-1)
results_acc['LSTM'] = accuracy_score(y_test_encoded, y_pred_dl) * 100
metrics_data.append({
    'Model': 'LSTM',
    'Precision': precision_score(y_test_encoded, y_pred_dl, average='weighted'),
    'Recall': recall_score(y_test_encoded, y_pred_dl, average='weighted'),
    'F1-score': f1_score(y_test_encoded, y_pred_dl, average='weighted')
})

loss, accuracy = lstm_model.evaluate(X_test_pad, y_test_encoded)
print(f'Model Accuracy (LSTM) : {accuracy * 100}')

print("\n--- Final Performance Table ---")
performance_df = pd.DataFrame(metrics_data).drop_duplicates(subset=['Model'])
performance_df['Accuracy'] = performance_df['Model'].map(lambda x: results_acc[x]/100)
print(performance_df.round(3))

# Accuracy Graph
plt.figure(figsize=(10, 5))
sns.barplot(x=list(results_acc.keys()), y=list(results_acc.values()), hue=list(results_acc.keys()), palette='Blues_d', legend=False)
plt.title('Comparison of Model Accuracies (%)')
plt.show()

# Metrics Graph
performance_df.set_index('Model')[['Precision', 'Recall', 'F1-score']].plot(kind='bar', figsize=(12, 6))
plt.title('Performance Evaluation Metrics')
plt.show()

# Ensure cell gJ-kyLk1Svq3 is executed before this cell to define y_test_encoded and y_pred_dl.

# ১. কনফিউশন ম্যাট্রিক্স ক্যালকুলেট করা
# y_test (আসল লেবেল) এবং y_pred_dl (মডেলের প্রেডিকশন)
cm = confusion_matrix(y_test_encoded, y_pred_dl)

# ২. ক্লাসের নামগুলো সেট করা (আপনার CSV ফাইল অনুযায়ী)
# ০ = Hate Speech, ১ = Offensive, ২ = Neither
class_names = ['Hate Speech', 'Offensive', 'Neither']

# ৩. ভিজ্যুয়ালাইজেশন (Heatmap)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names,
            annot_kws={"size": 14}) # সংখ্যার সাইজ বড় করার জন্য

# টাইটেল এবং লেবেল সেট করা
plt.title('Confusion Matrix: Hate Speech Detection System', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Predicted Class', fontsize=14, fontweight='bold')
plt.ylabel('True Class', fontsize=14, fontweight='bold')

# ৪. গ্রাফটি সুন্দরভাবে দেখানোর জন্য অ্যাডজাস্টমেন্ট
plt.xticks(fontsize=12)
plt.yticks(fontsize=12, rotation=0)
plt.tight_layout()

# ৫. সরাসরি ছবি হিসেবে সেভ করা (রিপোর্টের জন্য সুবিধাজনক)
plt.savefig('confusion_matrix_final.png', dpi=300)

# আউটপুট দেখানো
plt.show()